name: Build and push to TdA

on: [push]

env:
  SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
  SUPABASE_URL: ${{ secrets.SUPABASE_URL }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Check Out Repo
        uses: actions/checkout@v3
        
      - name: Make an .env file
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          envkey_SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          directory: './'
          file_name: '.env'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build
        uses: docker/build-push-action@v3
        with:
          context: ./
          tags: tda-nuxt:latest
          outputs: type=docker,dest=/tmp/tda-nuxt.tar

      - name: Upload to TdA
        uses: Tour-de-App/upload-app@tda-24
        with:
          team_secret: ${{ secrets.TEAM_SECRET }}
          image_name: tda-nuxt
          image_path: /tmp/tda-nuxt.tar
