name: Build and push to TdA

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      PROJECT_ID: jeyqlbttyosywybqsvmj

    steps:

      - uses: actions/checkout@v3
      - uses: supabase/setup-cli@v1
        with:
          version: latest
      - run: supabase init
      - run: supabase functions deploy github-action-deploy --project-ref $PROJECT_ID

      - name: Check Out Repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build
        uses: docker/build-push-action@v3
        with:
          context: ./
          tags: tda-nuxt:latest
          outputs: type=docker,dest=/tmp/tda-nuxt.tar

      - name: Upload to TdA
        uses: Tour-de-App/upload-app@tda-24
        with:
          team_secret: ${{ secrets.TEAM_SECRET }}
          image_name: tda-nuxt
          image_path: /tmp/tda-nuxt.tar
